import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { supabaseAdmin } from "@/lib/supabase";

const VID_PATTERN = /VID-[A-Z0-9]+-[A-Z0-9]+-[A-Z0-9]+/i;

const VISION_PROMPT = `This is a data verification chart. Extract the following and return only a valid JSON object, nothing else:
{
  "veritas_id": "the Veritas ID starting with VID-",
  "values": [array of all numerical Y-axis values plotted on the line in chronological order left to right]
}
Example:
{"veritas_id": "VID-KEN-UNEM-FC7919", "values": [7.2, 7.8, 9.1, 11.3, 13.4]}`;

interface ClaudeVisionResult {
  veritas_id: string;
  values: number[];
}

interface Discrepancy {
  index: number;
  year: number;
  stored: number;
  extracted: number;
}

const TOLERANCE = 1.0;

function compareValues(
  stored: number[],
  extracted: number[],
  years: number[]
): { tampered: boolean; discrepancies: Discrepancy[] } {
  const discrepancies: Discrepancy[] = [];
  const len = Math.min(stored.length, extracted.length);

  for (let i = 0; i < len; i++) {
    if (Math.abs(stored[i] - extracted[i]) > TOLERANCE) {
      discrepancies.push({
        index: i,
        year: years[i] ?? i,
        stored: stored[i],
        extracted: extracted[i],
      });
    }
  }

  return { tampered: discrepancies.length > 0, discrepancies };
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { base64, mediaType } = body as {
      base64: string;
      mediaType: "image/png" | "image/jpeg";
    };

    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

    // Single Claude Vision call — extracts both veritas_id and values
    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-5",
      max_tokens: 1024,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image",
              source: {
                type: "base64",
                media_type: mediaType as "image/png" | "image/jpeg",
                data: base64,
              },
            },
            { type: "text", text: VISION_PROMPT },
          ],
        },
      ],
    });

    const textBlock = message.content.find((b) => b.type === "text");
    const rawText = textBlock ? textBlock.text.trim() : "";

    // Strip markdown code fences if present
    const cleaned = rawText
      .replace(/^```(?:json)?\s*/i, "")
      .replace(/\s*```$/, "")
      .trim();

    // Parse Claude's JSON response
    let visionResult: ClaudeVisionResult;
    try {
      visionResult = JSON.parse(cleaned) as ClaudeVisionResult;
    } catch {
      return NextResponse.json({
        success: false,
        reason:
          "Could not find a Veritas ID in this image. Make sure the full chart card is visible.",
      });
    }

    // Validate the extracted veritas_id
    const vidMatch = visionResult.veritas_id?.match(VID_PATTERN);
    if (!vidMatch) {
      return NextResponse.json({
        success: false,
        reason:
          "Could not find a Veritas ID in this image. Make sure the full chart card is visible.",
      });
    }

    const extractedId = vidMatch[0].toUpperCase();
    const extractedValues: number[] = Array.isArray(visionResult.values)
      ? visionResult.values.map(Number)
      : [];

    // Supabase lookup
    const { data, error } = await supabaseAdmin
      .from("veritas_records")
      .select("*")
      .eq("id", extractedId)
      .single();

    if (error || !data) {
      return NextResponse.json({
        success: false,
        reason: `No record found for Veritas ID ${extractedId}. This chart may not have been generated by Veritas ID.`,
      });
    }

    // Compare extracted values against stored values
    const { tampered, discrepancies } = compareValues(
      data.values as number[],
      extractedValues,
      data.years as number[]
    );

    return NextResponse.json({
      success: true,
      id: extractedId,
      tampered,
      extracted_values: extractedValues,
      stored_values: data.values,
      discrepancies,
      record: data,
    });
  } catch {
    return NextResponse.json(
      {
        success: false,
        reason: "An unexpected error occurred. Please try again.",
      },
      { status: 500 }
    );
  }
}
